<a href="https://colab.research.google.com/github/Priy-anshi/class_script/blob/main/Day2IntroToDataAnalysis%26PlottingUsingPython30thJune.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Github Upload

In [55]:
# import pandas as pd

# # Replace 'raw_github_url' with the raw URL of the CSV file
# raw_github_url = 'https://github.com/swcarpentry/python-novice-gapminder/blob/a6c060a7933df7c04c36fed588a5205fd884bbd8/episodes/data/asia_gdp_per_capita.csv'
# df_github = pd.read_csv(raw_github_url)
# df_github.head()

# Using Google Drive

In [56]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [57]:
url =  '/content/drive/MyDrive/Python Course Operations/gapminder_gdp_asia.csv'

In [58]:
import pandas as pd

In [59]:
df_asia = pd.read_csv(url)

In [60]:
df_asia

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Afghanistan,779.445314,820.853030,853.100710,836.197138,739.981106,786.113360,978.011439,852.395945,649.341395,635.341351,726.734055,974.580338
1,Bahrain,9867.084765,11635.799450,12753.275140,14804.672700,18268.658390,19340.101960,19211.147310,18524.024060,19035.579170,20292.016790,23403.559270,29796.048340
2,Bangladesh,684.244172,661.637458,686.341554,721.186086,630.233627,659.877232,676.981866,751.979403,837.810164,972.770035,1136.390430,1391.253792
3,Cambodia,368.469286,434.038336,496.913648,523.432314,421.624026,524.972183,624.475478,683.895573,682.303175,734.285170,896.226015,1713.778686
4,China,400.448611,575.987001,487.674018,612.705693,676.900092,741.237470,962.421381,1378.904018,1655.784158,2289.234136,3119.280896,4959.114854
5,Hong Kong China,3054.421209,3629.076457,4692.648272,6197.962814,8315.928145,11186.141250,14560.530510,20038.472690,24757.603010,28377.632190,30209.015160,39724.978670
6,India,546.565749,590.061996,658.347151,700.770611,724.032527,813.337323,855.723538,976.512676,1164.406809,1458.817442,1746.769454,2452.210407
7,Indonesia,749.681655,858.900271,849.289770,762.431772,1111.107907,1382.702056,1516.872988,1748.356961,2383.140898,3119.335603,2873.912870,3540.651564
8,Iran,3035.326002,3290.257643,4187.329802,5906.731805,9613.818607,11888.595080,7608.334602,6642.881371,7235.653188,8263.590301,9240.761975,11605.714490
9,Iraq,4129.766056,6229.333562,8341.737815,8931.459811,9576.037596,14688.235070,14517.907110,11643.572680,3745.640687,3076.239795,4390.717312,4471.061906
10,Israel,4086.522128,5385.278451,7105.630706,8393.741404,12786.932230,13306.619210,15367.029200,17122.479860,18051.522540,20896.609240,21905.595140,25523.277100
11,Japan,3216.956347,4317.694365,6576.649461,9847.788607,14778.786360,16610.377010,19384.105710,22375.941890,26824.895110,28816.584990,28604.591900,31656.068060
12,Jordan,1546.907807,1886.080591,2348.009158,2741.796252,2110.856309,2852.351568,4161.415959,4448.679912,3431.593647,3645.379572,3844.917194,4519.461171
13,Korea Dem. Rep.,1088.277758,1571.134655,1621.693598,2143.540609,3701.621503,4106.301249,4106.525293,4106.492315,3726.063507,1690.756814,1646.758151,1593.065480
14,Korea Rep.,1030.592226,1487.593537,1536.344387,2029.228142,3030.876650,4657.221020,5622.942464,8533.088805,12104.278720,15993.527960,19233.988180,23348.139730
15,Kuwait,108382.352900,113523.132900,95458.111760,80894.883260,109347.867000,59265.477140,31354.035730,28118.429980,34932.919590,40300.619960,35110.105660,47306.989780
16,Lebanon,4834.804067,6089.786934,5714.560611,6006.983042,7486.384341,8659.696836,7640.519521,5377.091329,6890.806854,8754.963850,9313.938830,10461.058680
17,Malaysia,1831.132894,1810.066992,2036.884944,2277.742396,2849.094780,3827.921571,4920.355951,5249.802653,7277.912802,10132.909640,10206.977940,12451.655800
18,Mongolia,786.566857,912.662609,1056.353958,1226.041130,1421.741975,1647.511665,2000.603139,2338.008304,1785.402016,1902.252100,2140.739323,3095.772271
19,Myanmar,331.000000,350.000000,388.000000,349.000000,357.000000,371.000000,424.000000,385.000000,347.000000,415.000000,611.000000,944.000000
20,Nepal,545.865723,597.936356,652.396859,676.442225,674.788130,694.112440,718.373095,775.632450,897.740360,1010.892138,1057.206311,1091.359778
21,Oman,1828.230307,2242.746551,2924.638113,4720.942687,10618.038550,11848.343920,12954.791010,18115.223130,18616.706910,19702.055810,19774.836870,22316.192870
22,Pakistan,684.597144,747.083529,803.342742,942.408259,1049.938981,1175.921193,1443.429832,1704.686583,1971.829464,2049.350521,2092.712441,2605.947580
23,Philippines,1272.880995,1547.944844,1649.552153,1814.127430,1989.374070,2373.204287,2603.273765,2189.634995,2279.324017,2536.534925,2650.921068,3190.481016
24,Saudi Arabia,6459.554823,8157.591248,11626.419750,16903.048860,24837.428650,34167.762600,33693.175250,21198.261360,24841.617770,20586.690190,19014.541180,21654.831940
25,Singapore,2315.138227,2843.104409,3674.735572,4977.418540,8597.756202,11210.089480,15169.161120,18861.530810,24769.891200,33519.476600,36023.105400,47143.179640
26,Sri Lanka,1083.532030,1072.546602,1074.471960,1135.514326,1213.395530,1348.775651,1648.079789,1876.766827,2153.739222,2664.477257,3015.378833,3970.095407
27,Syria,1643.485354,2117.234893,2193.037133,1881.923632,2571.423014,3195.484582,3761.837715,3116.774285,3340.542768,4014.238972,4090.925331,4184.548089
28,Taiwan,1206.947913,1507.861290,1822.879028,2643.858681,4062.523897,5596.519826,7426.354774,11054.561750,15215.657900,20206.820980,23235.423290,28718.276840
29,Thailand,757.797418,793.577415,1002.199172,1295.460660,1524.358936,1961.224635,2393.219781,2982.653773,4616.896545,5852.625497,5913.187529,7458.396327
30,Vietnam,605.066492,676.285448,772.049160,637.123289,699.501644,713.537120,707.235786,820.799445,989.023149,1385.896769,1764.456677,2441.576404
31,West Bank and Gaza,1515.592329,1827.067742,2198.956312,2649.715007,3133.409277,3682.831494,4336.032082,5107.197384,6017.654756,7110.667619,4515.487575,3025.349798
32,Yemen Rep.,781.717576,804.830455,825.623201,862.442146,1265.047031,1829.765177,1977.557010,1971.741538,1879.496673,2117.484526,2234.820827,2280.769906

In [61]:
df_movies= pd.read_csv('/content/drive/MyDrive/Python Course Operations/movie.csv')

In [62]:
df_asia = pd.read_csv(url, index_col='country')
print(df_asia)

                    gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country
Afghanistan             779.445314      820.853030      853.100710
Bahrain                9867.084765    11635.799450    12753.275140
Bangladesh              684.244172      661.637458      686.341554
Cambodia                368.469286      434.038336      496.913648
China                   400.448611      575.987001      487.674018
Hong Kong China        3054.421209     3629.076457     4692.648272
India                   546.565749      590.061996      658.347151
Indonesia               749.681655      858.900271      849.289770
Iran                   3035.326002     3290.257643     4187.329802
Iraq                   4129.766056     6229.333562     8341.737815
Israel                 4086.522128     5385.278451     7105.630706
Japan                  3216.956347     4317.694365     6576.649461
Jordan                 1546.907807     1886.080591     2348.009158
Korea Dem. Rep.        1088.277758     1571.134655     1621.693598
Korea Rep.             1030.592226     1487.593537     1536.344387
Kuwait               108382.352900   113523.132900    95458.111760
Lebanon                4834.804067     6089.786934     5714.560611
Malaysia               1831.132894     1810.066992     2036.884944
Mongolia                786.566857      912.662609     1056.353958
Myanmar                 331.000000      350.000000      388.000000
Nepal                   545.865723      597.936356      652.396859
Oman                   1828.230307     2242.746551     2924.638113
Pakistan                684.597144      747.083529      803.342742
Philippines            1272.880995     1547.944844     1649.552153
Saudi Arabia           6459.554823     8157.591248    11626.419750
Singapore              2315.138227     2843.104409     3674.735572
Sri Lanka              1083.532030     1072.546602     1074.471960
Syria                  1643.485354     2117.234893     2193.037133
Taiwan                 1206.947913     1507.861290     1822.879028
Thailand                757.797418      793.577415     1002.199172
Vietnam                 605.066492      676.285448      772.049160
West Bank and Gaza     1515.592329     1827.067742     2198.956312
Yemen Rep.              781.717576      804.830455      825.623201

                    gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
country
Afghanistan             836.197138      739.981106      786.113360
Bahrain               14804.672700    18268.658390    19340.101960
Bangladesh              721.186086      630.233627      659.877232
Cambodia                523.432314      421.624026      524.972183
China                   612.705693      676.900092      741.237470
Hong Kong China        6197.962814     8315.928145    11186.141250
India                   700.770611      724.032527      813.337323
Indonesia               762.431772     1111.107907     1382.702056
Iran                   5906.731805     9613.818607    11888.595080
Iraq                   8931.459811     9576.037596    14688.235070
Israel                 8393.741404    12786.932230    13306.619210
Japan                  9847.788607    14778.786360    16610.377010
Jordan                 2741.796252     2110.856309     2852.351568
Korea Dem. Rep.        2143.540609     3701.621503     4106.301249
Korea Rep.             2029.228142     3030.876650     4657.221020
Kuwait                80894.883260   109347.867000    59265.477140
Lebanon                6006.983042     7486.384341     8659.696836
Malaysia               2277.742396     2849.094780     3827.921571
Mongolia               1226.041130     1421.741975     1647.511665
Myanmar                 349.000000      357.000000      371.000000
Nepal                   676.442225      674.788130      694.112440
Oman                   4720.942687    10618.038550    11848.343920
Pakistan                942.408259     1049.938981     1175.921193
Philippines            1814.127430     1989.374070     2373.204287
Saudi Arabia          16903.048860    24837.428650    34167.762600
Singapore              4977.418540     8597.756202    11210.089480
Sri Lanka              1135.514326     1213.395530     1348.775651
Syria                  1881.923632     2571.423014     3195.484582
Taiwan                 2643.858681     4062.523897     5596.519826
Thailand               1295.460660     1524.358936     1961.224635
Vietnam                 637.123289      699.501644      713.537120
West Bank and Gaza     2649.715007     3133.409277     3682.831494
Yemen Rep.              862.442146     1265.047031     1829.765177

                    gdpPercap_1982  gdpPercap_1987  gdpPercap_1992  \
country
Afghanistan             978.011439      852.395945      649.341395
Bahrain               19211.147310    18524.024060    19035.579170
Bangladesh              676.981866      751.979403      837.810164
Cambodia                624.475478      683.895573      682.303175
China                   962.421381     1378.904018     1655.784158
Hong Kong China       14560.530510    20038.472690    24757.603010
India                   855.723538      976.512676     1164.406809
Indonesia              1516.872988     1748.356961     2383.140898
Iran                   7608.334602     6642.881371     7235.653188
Iraq                  14517.907110    11643.572680     3745.640687
Israel                15367.029200    17122.479860    18051.522540
Japan                 19384.105710    22375.941890    26824.895110
Jordan                 4161.415959     4448.679912     3431.593647
Korea Dem. Rep.        4106.525293     4106.492315     3726.063507
Korea Rep.             5622.942464     8533.088805    12104.278720
Kuwait                31354.035730    28118.429980    34932.919590
Lebanon                7640.519521     5377.091329     6890.806854
Malaysia               4920.355951     5249.802653     7277.912802
Mongolia               2000.603139     2338.008304     1785.402016
Myanmar                 424.000000      385.000000      347.000000
Nepal                   718.373095      775.632450      897.740360
Oman                  12954.791010    18115.223130    18616.706910
Pakistan               1443.429832     1704.686583     1971.829464
Philippines            2603.273765     2189.634995     2279.324017
Saudi Arabia          33693.175250    21198.261360    24841.617770
Singapore             15169.161120    18861.530810    24769.891200
Sri Lanka              1648.079789     1876.766827     2153.739222
Syria                  3761.837715     3116.774285     3340.542768
Taiwan                 7426.354774    11054.561750    15215.657900
Thailand               2393.219781     2982.653773     4616.896545
Vietnam                 707.235786      820.799445      989.023149
West Bank and Gaza     4336.032082     5107.197384     6017.654756
Yemen Rep.             1977.557010     1971.741538     1879.496673

                    gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Afghanistan             635.341351      726.734055      974.580338
Bahrain               20292.016790    23403.559270    29796.048340
Bangladesh              972.770035     1136.390430     1391.253792
Cambodia                734.285170      896.226015     1713.778686
China                  2289.234136     3119.280896     4959.114854
Hong Kong China       28377.632190    30209.015160    39724.978670
India                  1458.817442     1746.769454     2452.210407
Indonesia              3119.335603     2873.912870     3540.651564
Iran                   8263.590301     9240.761975    11605.714490
Iraq                   3076.239795     4390.717312     4471.061906
Israel                20896.609240    21905.595140    25523.277100
Japan                 28816.584990    28604.591900    31656.068060
Jordan                 3645.379572     3844.917194     4519.461171
Korea Dem. Rep.        1690.756814     1646.758151     1593.065480
Korea Rep.            15993.527960    19233.988180    23348.139730
Kuwait                40300.619960    35110.105660    47306.989780
Lebanon                8754.963850     9313.938830    10461.058680
Malaysia              10132.909640    10206.977940    12451.655800
Mongolia               1902.252100     2140.739323     3095.772271
Myanmar                 415.000000      611.000000      944.000000
Nepal                  1010.892138     1057.206311     1091.359778
Oman                  19702.055810    19774.836870    22316.192870
Pakistan               2049.350521     2092.712441     2605.947580
Philippines            2536.534925     2650.921068     3190.481016
Saudi Arabia          20586.690190    19014.541180    21654.831940
Singapore             33519.476600    36023.105400    47143.179640
Sri Lanka              2664.477257     3015.378833     3970.095407
Syria                  4014.238972     4090.925331     4184.548089
Taiwan                20206.820980    23235.423290    28718.276840
Thailand               5852.625497     5913.187529     7458.396327
Vietnam                1385.896769     1764.456677     2441.576404
West Bank and Gaza     7110.667619     4515.487575     3025.349798
Yemen Rep.             2117.484526     2234.820827     2280.769906

In [63]:
df_asia.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, Afghanistan to Yemen Rep.
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gdpPercap_1952  33 non-null     float64
 1   gdpPercap_1957  33 non-null     float64
 2   gdpPercap_1962  33 non-null     float64
 3   gdpPercap_1967  33 non-null     float64
 4   gdpPercap_1972  33 non-null     float64
 5   gdpPercap_1977  33 non-null     float64
 6   gdpPercap_1982  33 non-null     float64
 7   gdpPercap_1987  33 non-null     float64
 8   gdpPercap_1992  33 non-null     float64
 9   gdpPercap_1997  33 non-null     float64
 10  gdpPercap_2002  33 non-null     float64
 11  gdpPercap_2007  33 non-null     float64
dtypes: float64(12)
memory usage: 3.4+ KB

In [64]:
print(df_asia.columns)

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')

In [65]:
df_asia = df_asia.T

In [66]:
df_asia

country,Afghanistan,Bahrain,Bangladesh,Cambodia,China,Hong Kong China,India,Indonesia,Iran,Iraq,...,Philippines,Saudi Arabia,Singapore,Sri Lanka,Syria,Taiwan,Thailand,Vietnam,West Bank and Gaza,Yemen Rep.
gdpPercap_1952,779.445314,9867.084765,684.244172,368.469286,400.448611,3054.421209,546.565749,749.681655,3035.326002,4129.766056,...,1272.880995,6459.554823,2315.138227,1083.532030,1643.485354,1206.947913,757.797418,605.066492,1515.592329,781.717576
gdpPercap_1957,820.853030,11635.799450,661.637458,434.038336,575.987001,3629.076457,590.061996,858.900271,3290.257643,6229.333562,...,1547.944844,8157.591248,2843.104409,1072.546602,2117.234893,1507.861290,793.577415,676.285448,1827.067742,804.830455
gdpPercap_1962,853.100710,12753.275140,686.341554,496.913648,487.674018,4692.648272,658.347151,849.289770,4187.329802,8341.737815,...,1649.552153,11626.419750,3674.735572,1074.471960,2193.037133,1822.879028,1002.199172,772.049160,2198.956312,825.623201
gdpPercap_1967,836.197138,14804.672700,721.186086,523.432314,612.705693,6197.962814,700.770611,762.431772,5906.731805,8931.459811,...,1814.127430,16903.048860,4977.418540,1135.514326,1881.923632,2643.858681,1295.460660,637.123289,2649.715007,862.442146
gdpPercap_1972,739.981106,18268.658390,630.233627,421.624026,676.900092,8315.928145,724.032527,1111.107907,9613.818607,9576.037596,...,1989.374070,24837.428650,8597.756202,1213.395530,2571.423014,4062.523897,1524.358936,699.501644,3133.409277,1265.047031
gdpPercap_1977,786.113360,19340.101960,659.877232,524.972183,741.237470,11186.141250,813.337323,1382.702056,11888.595080,14688.235070,...,2373.204287,34167.762600,11210.089480,1348.775651,3195.484582,5596.519826,1961.224635,713.537120,3682.831494,1829.765177
gdpPercap_1982,978.011439,19211.147310,676.981866,624.475478,962.421381,14560.530510,855.723538,1516.872988,7608.334602,14517.907110,...,2603.273765,33693.175250,15169.161120,1648.079789,3761.837715,7426.354774,2393.219781,707.235786,4336.032082,1977.557010
gdpPercap_1987,852.395945,18524.024060,751.979403,683.895573,1378.904018,20038.472690,976.512676,1748.356961,6642.881371,11643.572680,...,2189.634995,21198.261360,18861.530810,1876.766827,3116.774285,11054.561750,2982.653773,820.799445,5107.197384,1971.741538
gdpPercap_1992,649.341395,19035.579170,837.810164,682.303175,1655.784158,24757.603010,1164.406809,2383.140898,7235.653188,3745.640687,...,2279.324017,24841.617770,24769.891200,2153.739222,3340.542768,15215.657900,4616.896545,989.023149,6017.654756,1879.496673
gdpPercap_1997,635.341351,20292.016790,972.770035,734.285170,2289.234136,28377.632190,1458.817442,3119.335603,8263.590301,3076.239795,...,2536.534925,20586.690190,33519.476600,2664.477257,4014.238972,20206.820980,5852.625497,1385.896769,7110.667619,2117.484526
gdpPercap_2002,726.734055,23403.559270,1136.390430,896.226015,3119.280896,30209.015160,1746.769454,2873.912870,9240.761975,4390.717312,...,2650.921068,19014.541180,36023.105400,3015.378833,4090.925331,23235.423290,5913.187529,1764.456677,4515.487575,2234.820827
gdpPercap_2007,974.580338,29796.048340,1391.253792,1713.778686,4959.114854,39724.978670,2452.210407,3540.651564,11605.714490,4471.061906,...,3190.481016,21654.831940,47143.179640,3970.095407,4184.548089,28718.276840,7458.396327,2441.576404,3025.349798,2280.769906

In [67]:
df_asia.describe()

country,Afghanistan,Bahrain,Bangladesh,Cambodia,China,Hong Kong China,India,Indonesia,Iran,Iraq,...,Philippines,Saudi Arabia,Singapore,Sri Lanka,Syria,Taiwan,Thailand,Vietnam,West Bank and Gaza,Yemen Rep.
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,...,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,802.674598,18077.663945,817.558818,675.367824,1488.307694,16228.700865,1057.296307,1741.365360,7376.582905,7811.809117,...,2174.771130,20261.743635,17425.382267,1854.731120,3009.287981,10224.807181,3045.966474,1017.712615,3759.996781,1569.274672
std,108.202929,5415.413364,235.079648,360.254866,1370.628333,12207.329731,570.248221,996.510872,2954.183911,4150.266300,...,545.227957,8754.387440,14926.147774,934.689752,908.220166,9482.608281,2325.900032,567.482251,1716.840614,609.939160
min,635.341351,9867.084765,630.233627,368.469286,400.448611,3054.421209,546.565749,749.681655,3035.326002,3076.239795,...,1272.880995,6459.554823,2315.138227,1072.546602,1643.485354,1206.947913,757.797418,605.066492,1515.592329,781.717576
25%,736.669343,14291.823310,673.145764,481.194820,603.526020,5821.634179,690.164746,856.497646,5476.881304,4325.479498,...,1772.983611,15583.891582,4651.747798,1122.518752,2174.086573,2438.613768,1222.145288,693.697595,2537.025333,853.237410
50%,803.483195,18779.801615,703.763820,574.723831,851.829425,12873.335880,834.530430,1449.787522,7421.993895,7285.535689,...,2234.479506,20892.475775,13189.625300,1498.427720,3156.129434,6511.437300,2177.222208,742.793140,3408.120386,1854.630925
75%,852.572136,19578.080667,871.550132,696.492972,1814.146653,25662.610305,1238.009467,2505.833891,9334.026133,10092.921367,...,2553.219635,24838.475930,26957.287550,2281.423731,3824.938029,16463.448670,4925.828783,1088.241554,4663.415027,2012.538889
max,978.011439,29796.048340,1391.253792,1713.778686,4959.114854,39724.978670,2452.210407,3540.651564,11888.595080,14688.235070,...,3190.481016,34167.762600,47143.179640,3970.095407,4184.548089,28718.276840,7458.396327,2441.576404,7110.667619,2280.769906

In [68]:
df_asia.describe(include='all')

country,Afghanistan,Bahrain,Bangladesh,Cambodia,China,Hong Kong China,India,Indonesia,Iran,Iraq,...,Philippines,Saudi Arabia,Singapore,Sri Lanka,Syria,Taiwan,Thailand,Vietnam,West Bank and Gaza,Yemen Rep.
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,...,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,802.674598,18077.663945,817.558818,675.367824,1488.307694,16228.700865,1057.296307,1741.365360,7376.582905,7811.809117,...,2174.771130,20261.743635,17425.382267,1854.731120,3009.287981,10224.807181,3045.966474,1017.712615,3759.996781,1569.274672
std,108.202929,5415.413364,235.079648,360.254866,1370.628333,12207.329731,570.248221,996.510872,2954.183911,4150.266300,...,545.227957,8754.387440,14926.147774,934.689752,908.220166,9482.608281,2325.900032,567.482251,1716.840614,609.939160
min,635.341351,9867.084765,630.233627,368.469286,400.448611,3054.421209,546.565749,749.681655,3035.326002,3076.239795,...,1272.880995,6459.554823,2315.138227,1072.546602,1643.485354,1206.947913,757.797418,605.066492,1515.592329,781.717576
25%,736.669343,14291.823310,673.145764,481.194820,603.526020,5821.634179,690.164746,856.497646,5476.881304,4325.479498,...,1772.983611,15583.891582,4651.747798,1122.518752,2174.086573,2438.613768,1222.145288,693.697595,2537.025333,853.237410
50%,803.483195,18779.801615,703.763820,574.723831,851.829425,12873.335880,834.530430,1449.787522,7421.993895,7285.535689,...,2234.479506,20892.475775,13189.625300,1498.427720,3156.129434,6511.437300,2177.222208,742.793140,3408.120386,1854.630925
75%,852.572136,19578.080667,871.550132,696.492972,1814.146653,25662.610305,1238.009467,2505.833891,9334.026133,10092.921367,...,2553.219635,24838.475930,26957.287550,2281.423731,3824.938029,16463.448670,4925.828783,1088.241554,4663.415027,2012.538889
max,978.011439,29796.048340,1391.253792,1713.778686,4959.114854,39724.978670,2452.210407,3540.651564,11888.595080,14688.235070,...,3190.481016,34167.762600,47143.179640,3970.095407,4184.548089,28718.276840,7458.396327,2441.576404,7110.667619,2280.769906

In [69]:
help(df_asia.head)

Help on method head in module pandas.core.generic:

head(n: 'int' = 5) -> 'NDFrameT' method of pandas.core.frame.DataFrame instance
    Return the first `n` rows.

    This function returns the first `n` rows for the object based
    on position. It is useful for quickly testing if your object
    has the right type of data in it.

    For negative values of `n`, this function returns all rows except
    the last `|n|` rows, equivalent to ``df[:n]``.

    If n is larger than the number of rows, this function returns all rows.

    Parameters
    ----------
    n : int, default 5
        Number of rows to select.

    Returns
    -------
    same type as caller
        The first `n` rows of the caller object.

    See Also
    --------
    DataFrame.tail: Returns the last `n` rows.

    Examples
    --------
    >>> df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
    ...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
    >>> df
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey
    5     parrot
    6      shark
    7      whale
    8      zebra

    Viewing the first 5 lines

    >>> df.head()
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey

    Viewing the first `n` lines (three in this case)

    >>> df.head(3)
          animal
    0  alligator
    1        bee
    2     falcon

    For negative values of `n`

    >>> df.head(-3)
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey
    5     parrot

In [70]:
df_asia.head()

country,Afghanistan,Bahrain,Bangladesh,Cambodia,China,Hong Kong China,India,Indonesia,Iran,Iraq,...,Philippines,Saudi Arabia,Singapore,Sri Lanka,Syria,Taiwan,Thailand,Vietnam,West Bank and Gaza,Yemen Rep.
gdpPercap_1952,779.445314,9867.084765,684.244172,368.469286,400.448611,3054.421209,546.565749,749.681655,3035.326002,4129.766056,...,1272.880995,6459.554823,2315.138227,1083.532030,1643.485354,1206.947913,757.797418,605.066492,1515.592329,781.717576
gdpPercap_1957,820.853030,11635.799450,661.637458,434.038336,575.987001,3629.076457,590.061996,858.900271,3290.257643,6229.333562,...,1547.944844,8157.591248,2843.104409,1072.546602,2117.234893,1507.861290,793.577415,676.285448,1827.067742,804.830455
gdpPercap_1962,853.100710,12753.275140,686.341554,496.913648,487.674018,4692.648272,658.347151,849.289770,4187.329802,8341.737815,...,1649.552153,11626.419750,3674.735572,1074.471960,2193.037133,1822.879028,1002.199172,772.049160,2198.956312,825.623201
gdpPercap_1967,836.197138,14804.672700,721.186086,523.432314,612.705693,6197.962814,700.770611,762.431772,5906.731805,8931.459811,...,1814.127430,16903.048860,4977.418540,1135.514326,1881.923632,2643.858681,1295.460660,637.123289,2649.715007,862.442146
gdpPercap_1972,739.981106,18268.658390,630.233627,421.624026,676.900092,8315.928145,724.032527,1111.107907,9613.818607,9576.037596,...,1989.374070,24837.428650,8597.756202,1213.395530,2571.423014,4062.523897,1524.358936,699.501644,3133.409277,1265.047031

In [71]:
df_asia.tail()

country,Afghanistan,Bahrain,Bangladesh,Cambodia,China,Hong Kong China,India,Indonesia,Iran,Iraq,...,Philippines,Saudi Arabia,Singapore,Sri Lanka,Syria,Taiwan,Thailand,Vietnam,West Bank and Gaza,Yemen Rep.
gdpPercap_1987,852.395945,18524.02406,751.979403,683.895573,1378.904018,20038.47269,976.512676,1748.356961,6642.881371,11643.572680,...,2189.634995,21198.26136,18861.53081,1876.766827,3116.774285,11054.56175,2982.653773,820.799445,5107.197384,1971.741538
gdpPercap_1992,649.341395,19035.57917,837.810164,682.303175,1655.784158,24757.60301,1164.406809,2383.140898,7235.653188,3745.640687,...,2279.324017,24841.61777,24769.89120,2153.739222,3340.542768,15215.65790,4616.896545,989.023149,6017.654756,1879.496673
gdpPercap_1997,635.341351,20292.01679,972.770035,734.285170,2289.234136,28377.63219,1458.817442,3119.335603,8263.590301,3076.239795,...,2536.534925,20586.69019,33519.47660,2664.477257,4014.238972,20206.82098,5852.625497,1385.896769,7110.667619,2117.484526
gdpPercap_2002,726.734055,23403.55927,1136.390430,896.226015,3119.280896,30209.01516,1746.769454,2873.912870,9240.761975,4390.717312,...,2650.921068,19014.54118,36023.10540,3015.378833,4090.925331,23235.42329,5913.187529,1764.456677,4515.487575,2234.820827
gdpPercap_2007,974.580338,29796.04834,1391.253792,1713.778686,4959.114854,39724.97867,2452.210407,3540.651564,11605.714490,4471.061906,...,3190.481016,21654.83194,47143.17964,3970.095407,4184.548089,28718.27684,7458.396327,2441.576404,3025.349798,2280.769906

In [72]:
df_asia.iloc[0,0]

779.4453145

In [73]:
df_asia.loc['gdpPercap_1952',:]

country
Afghanistan              779.445314
Bahrain                 9867.084765
Bangladesh               684.244172
Cambodia                 368.469286
China                    400.448611
Hong Kong China         3054.421209
India                    546.565749
Indonesia                749.681655
Iran                    3035.326002
Iraq                    4129.766056
Israel                  4086.522128
Japan                   3216.956347
Jordan                  1546.907807
Korea Dem. Rep.         1088.277758
Korea Rep.              1030.592226
Kuwait                108382.352900
Lebanon                 4834.804067
Malaysia                1831.132894
Mongolia                 786.566857
Myanmar                  331.000000
Nepal                    545.865723
Oman                    1828.230307
Pakistan                 684.597144
Philippines             1272.880995
Saudi Arabia            6459.554823
Singapore               2315.138227
Sri Lanka               1083.532030
Syria                   1643.485354
Taiwan                  1206.947913
Thailand                 757.797418
Vietnam                  605.066492
West Bank and Gaza      1515.592329
Yemen Rep.               781.717576
Name: gdpPercap_1952, dtype: float64

In [74]:
df_asia.loc[:,'Taiwan']

gdpPercap_1952     1206.947913
gdpPercap_1957     1507.861290
gdpPercap_1962     1822.879028
gdpPercap_1967     2643.858681
gdpPercap_1972     4062.523897
gdpPercap_1977     5596.519826
gdpPercap_1982     7426.354774
gdpPercap_1987    11054.561750
gdpPercap_1992    15215.657900
gdpPercap_1997    20206.820980
gdpPercap_2002    23235.423290
gdpPercap_2007    28718.276840
Name: Taiwan, dtype: float64

In [75]:
df_asia.loc['gdpPercap_1952':'gdpPercap_2007','Pakistan']

gdpPercap_1952     684.597144
gdpPercap_1957     747.083529
gdpPercap_1962     803.342742
gdpPercap_1967     942.408259
gdpPercap_1972    1049.938981
gdpPercap_1977    1175.921193
gdpPercap_1982    1443.429832
gdpPercap_1987    1704.686583
gdpPercap_1992    1971.829464
gdpPercap_1997    2049.350521
gdpPercap_2002    2092.712441
gdpPercap_2007    2605.947580
Name: Pakistan, dtype: float64

In [76]:
df_asia.loc['gdpPercap_1957'].max()

113523.1329

In [77]:
df_asia.loc['gdpPercap_1957',:].max()

113523.1329